pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:roiupagency/bitbucket-to-github.git
          - cd RepoName.git
          - git push --mirror git@github.com:devsroiup/bitbucket-to-github.git